version: "2"

services:
  backend:
    image: r.deso.tech/dockerhub/library/registry:2
  frontend:
    image: r.deso.tech/dockerhub/jpetazzo/hamba
    command: 5000 backend:5000
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - backend
