version: "2"
services:
  bootstrap:
    image: r.deso.tech/dockerhub/jpetazzo/consul
    command: agent -server -bootstrap
    container_name: bootstrap
  server:
    image: r.deso.tech/dockerhub/jpetazzo/consul
    command: agent -server -join bootstrap -join server
  client:
    image: r.deso.tech/dockerhub/jpetazzo/consul
    command: members -rpc-addr server:8400
